export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_FAILURE="GET_DATA_FAILURE";

export const GET_IMAGES_REQUEST="GET_IMAGES_REQUEST";
export const GET_IMAGES_SUCCESS="GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAILURE="GET_IMAGES_FAILURE";


export const UPDATE_DATA_REQUEST="UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS="UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAILURE="UPDATE_DATA_FAILURE";

export const UPDATE_IMAGE_REQUEST="UPDATE_IMAGE_REQUEST";
export const UPDATE_IMAGE_SUCCESS="UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_FAILURE="UPDATE_IMAGE_FAILURE";